_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TRAIN: ("balloon_train", )
  TEST : ("balloon_val", )
MODEL:
  BACKBONE: 
    NAME : "build_resnet_fpn_backbone"
    FREEZE_AT: 2
  # model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml")
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/138205316/model_final_a3ec72.pkl"
  MASK_ON: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE : 128
    NUM_CLASSES : 1
  RESNETS:
    DEPTH: 101
SOLVER:
  BASE_LR : 0.00025
  IMS_PER_BATCH : 2
  MAX_ITER: 300
TEST:  
  EVAL_PERIOD : 100
OUTPUT_DIR: "/content/cyril-fv-test-mask-rcnn/tasks_1_3/models/ResNet-101-FPN/"