_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TRAIN: ("balloon_train", )
  TEST : ("balloon_val", )
MODEL:
  BACKBONE:
    NAME: build_mobilenet_fpn_backbone
    FREEZE_AT: 0
  WEIGHTS: https://dl.dropbox.com/s/q4iceofvlcu207c/faster_mobilenetv2_FPNLite_ms_3x.pth
  MASK_ON: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE : 128
    NUM_CLASSES : 1
SOLVER:
  BASE_LR : 0.025
  IMS_PER_BATCH : 2
  MAX_ITER: 3000
  STEPS: (800, 1200, 2000)
TEST:  
  EVAL_PERIOD : 500
OUTPUT_DIR: "/content/cyril-fv-test-mask-rcnn/tasks_1_3/models/MobileNet-FPN/"