_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TRAIN: ("balloon_train", )
  TEST : ("balloon_val", )
MODEL:
  BACKBONE: 
    NAME : "build_resnet_fpn_backbone"
    FREEZE_AT: 2
  # model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE : 128
    NUM_CLASSES : 1
  RESNETS:
    DEPTH: 50
SOLVER:
  BASE_LR : 0.00025
  IMS_PER_BATCH : 2
  MAX_ITER: 300
TEST:  
  EVAL_PERIOD : 100
OUTPUT_DIR: "/content/computer-vision-REST-API/MaskRCNN_finetune/models/ResNet-50-FPN/"